springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger.html

jwt:
  secret: averygoodsecretnoonewilleverguessinamillionyears
  accessTokenExpiration: 600000
  refreshTokenExpiration: 3600000

spring:
  application:
    name: bweng-spring-rest-backend

  datasource:
    url: jdbc:mariadb://localhost:3306/spring
    username: springuser
    password: springpw
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

  minio:
    url: ${BUCKET_HOST:http://minio}
    port: ${BUCKET_PORT:9000}
    user: ${BUCKET_ACCESS_KEY:minioadmin}
    password: ${BUCKET_ACCESS_SECRET:minioadminpw}
    bucket: ${BUCKET_NAME:files}
  

