springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger.html

jwt:
  secret: averygoodsecretnoonewilleverguessinamillionyears
  accessTokenExpiration: 600000
  refreshTokenExpiration: 3600000

spring:
  application:
    name: bweng-spring-rest-backend

  datasource:
    url: jdbc:mariadb://localhost:3306/spring
    username: springuser
    password: springpw
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

minio:
  url: http://localhost
  port: 9000
  user: minioadmin
  password: minioadminpw
  bucket: files

file:
  allowed-types: image/jpeg, image/png, image/jpg, video/mp4
